### ISSUE TITLE
Dispute fee charged on parachain

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/tellor-parachain-contracts#14]
As per https://github.com/tellor-io/tellor-pallet/issues/12, you may no longer need the `_disputeFee` parameter at https://github.com/tellor-io/tellor-parachain-contracts/blob/3b7511105cb429f1789c77fc3f7a76394776c59d/src/ParachainGovernance.sol#L128

@oraclown

**Comment by oraclown** [comment]
> As per [tellor-io/tellor-pallet#12](https://github.com/tellor-io/tellor-pallet/issues/12), you may no longer need the `_disputeFee` parameter at
> 
> https://github.com/tellor-io/tellor-parachain-contracts/blob/3b7511105cb429f1789c77fc3f7a76394776c59d/src/ParachainGovernance.sol#L128
> 
> @oraclown
Thanks for spotting that. I'll remove it. 
- Are there any other transfers that are already happening on the oracle consumer side that I need to remove from [executeVote](https://github.com/tellor-io/tellor-parachain-contracts/blob/main/src/ParachainGovernance.sol#L351)?
- Basically, how should I communicate to the consumer chain that fees need to be given back/to different parties depending on the vote outcome? Anything to do with the slash amount handled on the evm compatible chain side, anything to do with dispute fee handled on the oracle consumer side? Seems like a `reportVoteExecuted` function that passes the result via xcm is needed, no?

**Comment by oraclown** [comment]
@evilrobot-01 Would like your confirmation on that thinking and the proposed function^

**Comment by evilrobot-01** [comment]
Yup, there are already three dispatchable functions in the pallet to handle the possible dispute outcomes, all restricted to only be called via governance:
- [`report_slash`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L1493): called when a dispute was succesful and reporter has been slashed
- [`report_invalid_dispute`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L1553): called when dispute determined to be invalid
- [`slash_dispute_initiator`](https://github.com/tellor-io/tellor-pallet/blob/0d5eb91197722547acc6ad97ea88f7bf0f4d0b15/src/lib.rs#L1568): called when a dispute fails and the dispute initiator is to be slashed of the dispute fee.

It might be a good opportunity to review the pallet implementation of these functions and how they align with the source smart contracts where the logic was ported from. You could then create a single `reportVoteExecuted` on your end as proposed, but then just have a different call encoding depending on result.

**Comment by oraclown** [comment]
I like the route of making a single `reportVoteExecuted` function. I'll look at those function implementations in the pallet.

**Comment by oraclown** [comment]
Some notes to help me think about this:
1. Dispute is started, dispute fee collected from initiator on oracle consumer chain, reporter slashed on evm chain
2. If vote passes
    a. slash amount transferred from gov to dispute initiator
    b. result is passed to oracle consumer chain, where dispute fees for each voting round are returned to dispute initiator
3. If vote is invalid
    a. slash amount transferred back to reporter from gov
    b. result is passed to oracle consumer chain, where dispute fees for each voting round are returned to initiator
4. If vote fails
    a. slash amount is transferred back to reporter from gov
    b. result is passed to oracle consumer chain, where dispute fees for each voting round are transferred to reporter


Based on above, the original [gov contract execute vote function](https://github.com/tellor-io/tellor-parachain-contracts/blob/main/lib/tellor/Governance.sol#L181), and the functions you linked to, I have questions and possible todos (that I can make issues for in `tellor-pallet` if you agree the functionality is missing):
- `report_slash` is called in `beginParachainDispute`, not in any condition of `executeVote` (this is the case already, nothing to do here)
- if the vote passes OR is invalid, I'm not seeing where the dispute fees are returned to the initiator in `lib.rs` in the funcs listed above, in `execute_vote` of `impls.rs`, or elsewhere when I search the repo using keywords. I'm possible missing these, or they haven't been implemented yet?
- if the vote fails, I don't see where dispute fees for each voting round are transferred to the reporter, or it's [not implemented](https://github.com/tellor-io/tellor-pallet/blob/main/src/lib.rs#L1576)

**Comment by evilrobot-01** [comment]
We will sync internally when I am back next week and update accordingly.
