### ISSUE TITLE
Confirm stake amount updates from oracle consumer chain passed to evm-compatible parachain

### ISSUE THREAD

**Issue by oraclown** [tellor-io/tellor-parachain-contracts#15]
## Original comment/question:
```
How are updates to the stake amount of an oracle consumer parachain delivered to the evm compatible chain?
```
## Response:
```
Currently the stake amount is just some number of TRB tokens which is pushed to staking contract on (re-)register. I know you have a TRBUSD feed but I couldn't see that this was needed this far. Happy to add in if required? We could then have that value pushed to staking contract on value submission for queryId, but that would be too chatty.
```
## Current thoughts/questions:
When someone stakes on the evm-compatible chain to enable reporting on an oracle consumer chain, it's just assumed that they're staking enough (that the stake amount set by the last `register` call is >= the current stake amount on the oracle consumer chain, so they'll be able to report).

The only place where the staker's tokens are messed with (on the evm-compatible side) by messages sent from the oracle consumer chain, are upon dispute initiation, where the staker/reporter of the disputed value is slashed. But in that case it doesn't matter if the slash amount is less/more than an outdated stake amount, as this is accounted for. 

After writing this, I think the issue can be closed, as there's no changes that need to be made on the contracts side regarding updating the stake amount.

@evilrobot-01 Could you point me to where the stake amount is updated on the oracle consumer chain side? Different players in the oracle system are incentivized to update the stake amount bc of price moves.

**Comment by oraclown** [comment]
Oh, based on your reply, `slash_dispute_initiator` or `report_slash` need to be called in the [tellor pallet](https://github.com/tellor-io/tellor-pallet/blob/main/src/lib.rs#L1568). Will make functions to call those.

**Comment by evilrobot-01** [comment]
https://github.com/tellor-io/tellor-parachain-contracts/issues/14#issuecomment-1488843332 lists the various outcomes and corresponding calls.
