### ISSUE TITLE
can stakeAmount arg be removed from register function?

### ISSUE THREAD

**Issue by tkernell** [tellor-io/tellor-parachain-contracts#17]
- why do we we pass in the stakeAmount arg in the ParachainRegistry register function? The stakeAmount changes, and it should be known by the consumerParachain already

**Comment by tkernell** [comment]
@evilrobot-01

**Comment by evilrobot-01** [comment]
The stake amount in the register function is the minimum stake amount of TRB per parachain, which was a request early on in the project. The parachain is to decide on the amount and provides it to the smart contracts via the register function when it registers to use the Tellor service, and can re-register at any point to amend this amount along with the other parameters. The parameter name was based on https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/contracts/TellorFlex.sol#L23 but perhaps there is a better name to use?

I just wanted to check if you were referring to the stake amount changing based on USD value, or whether you were perhaps referring to the stake amount of a reporter? There is obviously a little ambiguity between these two values...

**Comment by tkernell** [comment]
I was referring to the minimum USD _stakeAmount inputted into the Registry contract 
```solidity
function register(uint32 _paraId, uint8 _palletInstance, uint256 _stakeAmount)
```
I was just wondering why it is saved in the registration contract, as I don't believe it's actually used by the contracts on the EVM chain, other than just being saved to the `Parachain` struct. I would propose removing this argument.

**Comment by evilrobot-01** [comment]
I was under the impression that was the amount in TRB set by the parachain, but if a reporter needs to stake a standard 100 TRB/USD 1,500 (or more) for each parachain then it makes sense to remove and leave stake amounts completely up to the staking contract.

**Comment by tkernell** [comment]
Anyone should be able to stake any amount in the staking contract, and then it's up to the parachain to determine whether that staker can report / how frequently as a function of  the the current stake amount, and how much they have staked.

**Comment by evilrobot-01** [comment]
Makes sense, thanks!
