### ISSUE TITLE
`reportSlash()` should use account on destination chain for `reporter` parameter

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/tellor-parachain-contracts#51]
We need the `bytes` account of the reporter on the destination chain to be passed to `reportSlash()` to lookup the staker details (keyed by local account id) rather than the evm address.

`reportStakeWithdrawn()` also appears to be incorrect, as the `reporter` parameter passed again should be the `bytes` account instead of `address`.

**Comment by oraclown** [comment]
> We need the `bytes` account of the reporter on the destination chain to be passed to `reportSlash()` to lookup the staker details (keyed by local account id) rather than the evm address.
> 
> `reportStakeWithdrawn()` also appears to be incorrect, as the `reporter` parameter passed again should be the `bytes` account instead of `address`.

Sounds good. Is the `address _recipient` parameter needed at all, since `slashParachainReporter` will only ever be called by the governance contract, and the recipient will always be the governance contract?

**Comment by evilrobot-01** [comment]
Your call, but the recipient is included in the `SlashReported` event on the parachain, much the same as https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/contracts/TellorFlex.sol#L74.

I do see that it is currently expecting an `AccountIdOf<T>` for recipient on the pallet, due to previous setup limiting the dispute initiator to being a reporter, so I will either need to amend to `address` to match, or drop it based on your decision. 

Please let me know which you'd like as soon as you can, so I can get it done. 🙂

**Comment by oraclown** [comment]
> Your call, but the recipient is included in the `SlashReported` event on the parachain, much the same as https://github.com/tellor-io/tellorFlex/blob/3b3820f2111ec2813cb51455ef68cf0955c51674/contracts/TellorFlex.sol#L74. I feel it provides clarity on where the slash is from the context of the consumer parachain, allowing someone to then follow that back on the smart contract chain.
> 
> I do see that it is currently expecting an `AccountIdOf<T>` for `recipient` on the pallet, due to previous setup limiting the dispute initiator to being a reporter, so I will either need to amend to `address` to match, or drop it based on your decision.
> 
> Please let me know which you'd like as soon as you can, so I can get it done. 🙂

I think they'd know that it's originated from the gov contract since that isn't going to change, and they'd already know who's initiating the dispute (when `begin_dispute` is called).

So I vote to drop it.

I'll also need to update my test, as it doesn't reflect the actual case when the function is called. It incorrectly passes in the dispute initiator when `slashParachainReporter` is called:
```js
// Slash stake
        vm.startPrank(staking.governance());
        staking.slashParachainReporter(
            10, // _slashAmount
            fakeParaId, // _paraId
            paraOwner, // _reporter
            paraDisputer // _recipient
        );
```

**Comment by evilrobot-01** [comment]
Thanks! Will add an issue in the pallet repo to remove.
