### ISSUE TITLE
Increase time allowed for disputes to be opened in gov contract only

### ISSUE THREAD

**Issue by oraclown** [tellor-io/tellor-parachain-contracts#58]
It's possible that someone opens a new vote round on the oracle consumer parachain side, but it is prevented from being opened on the contracts side, since the tally date on both sides will differ by about 12 seconds (the time it takes for the `reportVoteTallied` message of the previous round to arrive at the pallet).

The solution I propose is similar to #49 : Increase the time window allowing new vote rounds to be opened ONLY on the contracts side. So in practice, on the oracle consumer parachain side (where new vote rounds are initiated), new vote rounds must still be started within a day, but the contracts will be more lenient to account for any weird delays in the new vote round message being passed from the pallet to the evm-compatible parachain where the gov contract is deployed, and for any delays in the `reportVoteTallied` message being passed in previous rounds.

**Comment by oraclown** [comment]
@tkernell @evilrobot-01 @themandalore @brendaloya thoughts?

**Comment by tkernell** [comment]
Oh good catch, gotta handle that latency.
