### ISSUE TITLE
stake amount remains the same after request withdraw and slashed from dispute?

### ISSUE THREAD

**Issue by oraclown** [tellor-io/tellor-parachain-contracts#74]
- In `testRequestWithdrawStakeThenDispute`, does the final staked and locked balance seem correct? Seems like final staked balance should `50`, or?
- To reproduce, run individual test with command `forge test -m testRequestWithdrawStakeThenDispute -vvv` on my branch, `handle-todos`

_sample output:_
```console
[PASS] testRequestWithdrawStakeThenDispute() (gas: 1472043)
Logs:
  starting stakedBalance: 0
  starting lockedBalance: 0
  starting bob balance: 200
  after staking stakedBalance: 100
  after staking lockedBalance: 0
  after staking bob balance: 100
  after withdraw request stakedBalance: 100
  after withdraw request lockedBalance: 100
  after withdraw request bob balance: 100
  after dispute stakedBalance: 100
  after dispute lockedBalance: 50
  after dispute bob balance: 100
```

**Comment by tkernell** [comment]
in `requestParachainStakeWithdraw`, we need to subtract the _amount from the stakedBalance
