### ISSUE TITLE
remove deregister?

### ISSUE THREAD

**Issue by tkernell** [tellor-io/tellor-parachain-contracts#76]
- do we need consumer parachains to be able to deregister, or can we remove this function?
- I would think we'd want to prevent deregistering while stakes still exist in the contract
- if we want to be able to shutdown the oracle on a consumer parachain, maybe this can be handled purely on the consumer parachain side?

**Comment by tkernell** [comment]
@evilrobot-01 thoughts?

**Comment by evilrobot-01** [comment]
Can easily remove the call from the pallet, it was just a courtesy function to remove state from contracts if no longer required.

I agree it should not be allowed if there is active stake. 

Is it perhaps a co-dependency issue in the contracts?

**Comment by tkernell** [comment]
I don't think there's much downside to just keeping old inactive parachain registrations in the EVM contract, as compared to the risks/complexity of allowing deregistration
