### ISSUE TITLE
Clarify optimization to-do

### ISSUE THREAD

**Issue by oraclown** [tellor-io/tellor-parachain-contracts#78]
- What's this one mean: `confirm optimisation for lookups based on parachain owner address over paraId` @evilrobot-01 ? Here's the location in src: [line 31](https://github.com/tellor-io/tellor-parachain-contracts/blob/main/src/ParachainRegistry.sol#L31)
- Can this be closed, as lookups already seem to be made using `address`?

**Comment by evilrobot-01** [comment]
It was to look at all the usage of parachain lookups to decide on whether it was better to key by id or address. 

Put another way, optimising for reads vs reverse lookups from id to address to then get parachain info.

**Comment by oraclown** [comment]
`getByAddress` used 3 times in other contracts. `getById` used 6 times in other contracts. Seems better to use `id` as key.
