### ISSUE TITLE
Remove confirmParachainStakeWithdrawRequest?

### ISSUE THREAD

**Issue by tkernell** [tellor-io/tellor-parachain-contracts#92]
There could be a few problems with the current implementation of the `_lockedBalanceConfirmed` accounting:
- if someone calls `requestParachainStakeWithdraw` 2x before fully withdrawing, the `_lockedBalanceConfirmed` is incorrect. 
- if someone calls `requestParachainStakeWithdraw(amount = 100)`, then re-stakes with `depositStake(amount = 50)`, then that stake is take from the `_lockedBalance`, and the `_lockedBalanceConfirmed` is now incorrect. We cannot just subtract 50 from `_lockedBalanceConfirmed` as it's possible that the `confirmParachainStakeWithdrawRequest(amount = 100)` message hasn't been received yet, and `_lockedBalanceConfirmed = 0`.

Instead of restructuring to make this work, maybe we should just remove`confirmParachainStakeWithdrawRequest` altogether. It was intended to ensure that stakes cannot be withdrawn until the consumer parachain confirms that it has reduced the reporter's stake amount, but I think it may not be worth the added complexity of doing this accounting. Plus, we already have the 7 day withdrawal period.

**Comment by oraclown** [comment]
I'm in favor of removing it entirely, given that the 7 day lock period leaves ample time for state update messages to pass between evm-compatible parachain and the oracle consumer parachain.
